    backend:
      name: github
      branch: master # Branch to update (optional; defaults to master)
      repo: tohitsugu/netlify	

    # These lines should *not* be indented
    media_folder: "static/img" # Media files will be stored in the repo under 
    public_folder: "/img" # The src attribute for 
    collections:
    -   name: docs
        label: "docs"
        folder: docs
        identifier_field: title
        extension: md
        widget: "list"
        create: true
        slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
        fields:
          - { name: title, label: Title, widget: string }
          - { name: author, label: Label, widget: string }
          - { name: authorURL, label: "Author URL", widget: string }
          - { name: authorFBID, label: "Author FBID", widget: number }
          - { name: body, label: Body, widget: markdown }
